services:
  db:
    image: postgres:15.4-alpine3.18
    restart: always
    container_name: md-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: md_db
      TZ: 'Europe/Warsaw'
    ports:
      - 5433:5432
    volumes:
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql